### ISSUE TITLE
url for 2019.3.0 seems to change

### ISSUE THREAD

**Issue by umegaya** [sttz/install-unity#25]
hi, thank you for your effort to maintain install-unity for new release 👍 

today I found 
https://unity3d.com/unity/whats-new/2019.2.x returns 200 but
https://unity3d.com/unity/whats-new/2019.3.0 returns 404 with curl. 

consequently install-unity cannot find url for 2019.3.0f3.

did you find new url pattern for new version? 

regards,

**Comment by sttz** [comment]
Thanks for the report. The issue is that 2019.3 hasn't actually been released yet. It's gotten the f build letter but is only a release candidate. The release notes are still on the beta page:
https://unity3d.com/unity/beta/2019.3.0f3

install-unity currently only looks at the build letter and therefore gets confused. There are other places where this is an issue, e.g. 2019.3.0f3 only gets discovered when you load beta releases but then gets installed if you select the latest stable version.

I haven't been sure what's the best way to fix this. I'll have to somehow mark the release candidates but then mostly have to figure out how to best represent that in the output.

**Comment by umegaya** [comment]
oic, thanks! it seems that we should wait for 2019.3.0f4 (or later GA version).

**Comment by umegaya** [comment]
they released 2019.3.0f5 but still release candidate... 
I'm worry about they apply same method for 2020.x 😞  
how do you think?

**Comment by sttz** [comment]
I've improved handling of release candidates in the latest version (2.7.0). Release candidates are now marked and treated as a beta where possible, the release notes url is now also correct.

Once a release candidate is promoted to be the final release, the rc status should be automatically removed and the release handled as a regular version.

Did you use the latest version and encountered any issues?
