### ISSUE TITLE
"cannot create extraction directory" when installing android package

### ISSUE THREAD

**Issue by taurawaxeye** [sttz/install-unity#31]
when running the following command 

`echo -e "****\nN" | sudo -S ./install-unity install 2020.3.24f1 --packages Android --data-path "/Users/*******/.jenkins/tools/downloadedFiles/unityInstallers/" --opt "installPathMac=/Applications/Unity_Installations/{major}.{minor}.{patch}{type}{build}" -y`

I get the following error

`cannot create extraction directory: /Applications/Unity/PlaybackEngines/AndroidPlayer/SDK No such file or directory`

what I am trying to do?
When our build pipeline starts I am trying to get the required Unity version installed. I'm dealing with a scenario where unity is already installed, but the android package for unity isn't.

if I run the command with `--packages Unity,Android` because unity is already installed, it wont progress forward to installing android.

**Comment by sttz** [comment]
Depending on the order the additional android packages would be installed, the `PlaybackEngines/AndroidPlayer/SDK` directory would not exist yet and cause `unzip` to fail. This order depends on how the packages are downloaded, which I think is the reason it would work when installing the editor with the Android packages and fail if installing the Android packages for an existing installation.

Should be fixed in [install-unity 2.10.2](https://github.com/sttz/install-unity/releases/tag/2.10.2).
