### ISSUE TITLE
Could not find any installed versions of Unity, after the download is over

### ISSUE THREAD

**Issue by mohammedbabelly** [sttz/install-unity#34]
Hey there, 

I'm using an M1 Mac server for this, and I'm facing the issue of not finding any installed Unity version when trying to run a project.

So first I installed a specific version using this command:
`sudo install-unity install 2021.3.9f1 -p Unity,Documentation --yes`

And the output was:

> Selected packages:
> - Documentation (350.00 MB)
> - Unity (2.76 GB)
> 
> 
> Unity 2021.3.9f1 (ad3870b89536) installed to: /Applications/Unity 2021.3.9f1

but when I try to run `install-unity run f` it says that 

> Could not find any installed versions of Unit

Notice that the editor is being installed to its path at `/Applications/Unity 2021.3.9f1` but it can't be found automatically.

**Comment by sttz** [comment]
install-unity uses Spotlight to find installed versions of Unity. Specifically, it runs the following command:
> mdfind kMDItemCFBundleIdentifier = 'com.unity3d.UnityEditor5.x' 

Do you maybe have Spotlight disabled on your server?

Otherwise, it can take some time for Spotlight to index the new Unity installation. Did you try waiting for a bit and re-running the `install-unity run` command?

**Comment by mohammedbabelly** [comment]
Ok, I enabled it using `sudo mdutil -a -i on /` and it works, thanks.

**Comment by sttz** [comment]
Great, added a warning when Spotlight is disabled for the next version, so this should be more obvious.
