### ISSUE TITLE
Can't install 2017.1.0f3?

### ISSUE THREAD

**Issue by Geri-Borbas** [sttz/install-unity#9]
Thanks for the awesome script! 🎉 
Hopefully I can make it work to automate Editor Test runners on Travis CI soon.

---

But seems I can't install ` ./install-unity.py --package Unity 2017.1.0f3`

```
Install Unity Script 0.0.9

Found 1 existing Unity installations:
- 5.6.2f1 (/Applications/Unity)

Updating outdated unity versions caches

Trying to select most recent known Unity version
ERROR: Could not find a Unity version that matches "2017.1.0f3"
```

However, it is released: https://unity3d.com/get-unity/download/archive

**Comment by eppz** [comment]
I still can't `./install-unity.py --packages 2017.1.0f1`.

**Comment by Geri-Borbas** [comment]
The official torrent says the current version number is `Unity-2017.1.0f3`.
Is there a change in hosting perhaps?

**Comment by sttz** [comment]
install-unity is looking for links to macOS editor installers on the download archive page. For some reason, there's only a link to the torrent for the 2017.1 release and so the script cannot find it.

I suspect this is an error on Unity's side and that they will eventually fix it. Therefore I want to wait for a bit instead of pushing a temporary fix on our end.

In the meantime, you can manually add 2017.1 to install-unity's version index:
`./install-unity.py --discover http://beta.unity3d.com/download/472613c02cf7/MacEditorInstaller/Unity-2017.1.0f3.pkg`

And the you can install it like normal:
`./install-unity.py --package Unity 2017.1.0f3`

I'll leave this issue open to track when they fix the archive page links and install-unity will work normally again.

**Comment by Geri-Borbas** [comment]
Thanks for getting back!

I saw that they have only torrent link published yet.
Will they ever be publish the rest?
**What if they gone torrent only?**

I think I'll use 5.6.2f3 on Travis until than.

**Comment by sttz** [comment]
If you look on the release notes page you see they still have all the regular links:
https://unity3d.com/unity/whats-new/unity-2017.1.0

You also get the regular installer when you click through to the download from the home page. So I don't think it makes any sense for them to push people to the torrent in the download archive and I hope they will fix it soon.

**Comment by Geri-Borbas** [comment]
Yay! 🎉 

```
...
== 2017.1 ==
- 2017.1.0f3

== 5.6 ==
- 5.6.2f1
- 5.6.1f1
- 5.6.0f3

== 5.5 ==
- 5.5.4f1
- 5.5.3f1
- 5.5.2f1
- 5.5.1f1
- 5.5.0f3
...
```
